# Generated by Django 5.2.4 on 2025-07-29 18:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('recipient', models.CharField(max_length=255)),
                ('template', models.TextField(help_text='Enter Here SQL query')),
                ('db_dsn', models.TextField(help_text='Database DSN')),
                ('last_executed_at', models.DateTimeField(blank=True, null=True)),
                ('execution_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QueryParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('string', 'String'), ('number', 'Number'), ('date', 'Date'), ('select', 'Select'), ('multiselect', 'MultiSelect'), ('checkbox', 'Checkbox')], max_length=20)),
                ('min_number', models.FloatField(blank=True, null=True)),
                ('max_number', models.FloatField(blank=True, null=True)),
                ('min_date', models.DateField(blank=True, null=True)),
                ('max_date', models.DateField(blank=True, null=True)),
                ('allowed_values', models.TextField(blank=True, help_text='Value1, Value2', null=True)),
                ('required', models.BooleanField(default=False)),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='queries.query')),
            ],
        ),
    ]
