# Generated by Django 5.2.4 on 2025-07-31 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
