# Generated by Django 5.2.4 on 2025-08-01 12:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0002_query_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queryparameter',
            name='type',
            field=models.CharField(blank=True, choices=[('string', 'String'), ('number', 'Number'), ('date', 'Date'), ('select', 'Select'), ('multiselect', 'MultiSelect')], max_length=20),
        ),
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request', models.TextField(help_text='SQL request')),
                ('response', models.TextField(blank=True, help_text='Ответ (result or error)', null=True)),
                ('response_code', models.PositiveIntegerField(default=0, help_text='response code(0 = success, 1 = error)')),
                ('response_time', models.FloatField(default=0.0, help_text='time of execution')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_logs', to='queries.query')),
            ],
        ),
    ]
