# Generated by Django 5.2.4 on 2025-08-09 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0003_alter_queryparameter_type_requestlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='queryparameter',
            name='string_value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
