# Generated by Django 5.2.4 on 2025-09-10 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0004_queryparameter_string_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queryparameter',
            name='string_value',
        ),
        migrations.AlterField(
            model_name='query',
            name='recipient',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
