# Generated by Django 5.2.4 on 2025-09-10 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0005_remove_queryparameter_string_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestlog',
            name='response_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
