# Generated by Django 5.2.4 on 2025-09-10 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0006_requestlog_response_json'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestlog',
            name='response',
        ),
    ]
