# Generated by Django 5.2.4 on 2025-09-10 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0007_remove_requestlog_response'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestlog',
            name='response_json',
        ),
        migrations.AddField(
            model_name='requestlog',
            name='response',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
