# Generated by Django 5.2.4 on 2025-09-10 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0008_remove_requestlog_response_json_requestlog_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestlog',
            name='parameters',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
